project:
  type: website

website:
  title: "RETINA Lab"
  
  favicon: "/images/avatar-nobackground.png"
  twitter-card:
      image: "/images/cover.png"
  open-graph:
      image: "/images/cover.png"
  
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research <br> Projects
      - href: publications.qmd
        text: Scholarly <br> Work
      - href: Conferences.qmd
        text: Conferences & <br> Engagements
      - href: awards.qmd
        text: Awards
      - href: SDG.qmd
        text: UN SDG <br> Alignment
    right:
      - href: https://prital.netlify.app/
        text: PI's Profile

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

